version: '3'
services:
    lk-sanmark-janus-dev:
        build:
            context: .
            dockerfile: dev.Dockerfile
        image: lk-sanmark-janus-dev
        ports:
        - 8000:80
        volumes:
        - ./src:/app
        env_file:
        - ./src/.env
