version: '3'
services:
    lk-sanmark-janus:
        build:
            context: .
            dockerfile: prod.Dockerfile
        image: lk-sanmark-janus
        ports:
        - 80:80
        env_file:
        - ./src/.env
